### PR TITLE
Add Homu

### LINKED ISSUE #34: Set up Homu
Now that we have a `.travis.yml` file (thanks to #26), it would be nice to have Homu set up for this repository.

Instructions are at https://github.com/servo/servo/wiki/Adding-a-repo-to-Homu; note that you'll need someone with admin perms for some of the steps.

### PR DESCRIPTION
**Pull request by Unpublished**
Fixes #34 

If I didn't miss anything all other steps should need admin permissions.

### CODE REVIEW

**Comment by Unpublished** [comment]
Forgot about the saltfs config https://github.com/servo/saltfs/pull/871, now mine part should be done.

**Comment by asajeffrey** [comment]
Cool. @jdm, the changes all look good to me, but I have precious little experience with behind-the-scenes homu.

**Comment by asajeffrey** [comment]
@jdm this PR is adding homu :)

**Pull request merged**
