### PR TITLE
adding the archives for Yahoo.com

### PR DESCRIPTION
**Pull request by Belwyyn**
I took the Yahoo directory for issues #8  and #15 and am adding in my results.

### CODE REVIEW

**Comment by asajeffrey** [comment]
It looks like you committed the archive directory, but the indexes directory is missing?

**Comment by asajeffrey** [comment]
@Belwyyn can you see what happened to the indexes?

**Comment by Belwyyn** [comment]
Sorry about the long delay again. Do you see the indexes directory now?

**Comment by asajeffrey** [comment]
Yay, the index is there now, thanks!

**Pull request merged**
