### PR TITLE
add web archive for youtube and update README

### LINKED ISSUE #20: Instructions should specify running wayback with the `--port 8321` option
Hey, I tried to do a sample record for example.com but wasn't able to successfully. Using MacOS 10.13.2. And using `proxychains4`.

This is what I tried in one window:
```
> virtualenv -p python3 venv
> source venv/bin/activate
> pip install git+https://github.com/ikreymer/pywb.git
> wb-manager init Example
> wayback --proxy Example --live --proxy-record --autoindex
[Errno 2] No such file or directory: './config.yaml'
2018-02-06 22:21:19,536: [INFO]: Proxy recording into collection "new"
2018-02-06 22:21:19,543: [INFO]: Auto-Indexing Enabled on "/Users/rzambre/Documents/servo/servo-warc-tests/collections", checking every 30 secs
2018-02-06 22:21:19,645: [INFO]: Starting Gevent Server on 8080
2018-02-06 22:21:19,646: [INFO]: Checking Collection: Amazon
2018-02-06 22:21:19,646: [INFO]: Checking Collection: Example
2018-02-06 22:21:19,646: [INFO]: Checking Collection: Google
2018-02-06 22:21:19,646: [INFO]: Checking Collection: youtube
2018-02-06 22:21:19,647: [INFO]: Checking Collection: new
2018-02-06 22:21:19,647: [INFO]: Checking Collection: WBEZ
```

Is that "[Errno 2] No such file or directory: './config.yaml'" expected?

And in another window I do this:
```
proxychains4 ../servo/mach run -r --certificate-path proxy-certs/pywb-ca.pem https://www.example.com/
```

Anything I am missing? When the page loads, I don't see any activity on the `wayback` shell.

### PR DESCRIPTION
**Pull request by aishpant**
The two patches implement #10 and fix #20 

There were a couple of things I noticed- it isn't immediately obvious that `/etc/proxychains.conf` needs to be modified (should this be made clearer?) and that the --port option was missing from the wayback commands.

### CODE REVIEW

**Comment by asajeffrey** [comment]
Thanks! I'll have a look when I get back in front of a computer!

**Comment by asajeffrey** [comment]
OK, I checked out the recording, it looks pretty good! A couple of nits:

* Some of the video thumbnails are missing. When you record the page I think you have to scroll down to get youtube to load the thumbnails.

* The banner ad is missing, I suspect this is due to it randomly selecting the ad, so there's not much we can do about this:

> Url Not Found
> The url https://pubads.g.doubleclick.net/gampad/ads?sz=850x250&gdfp_req=1&ad_rule=0&iu=/4061/com.ythome&impl=ifr&scp=ssl%3D1%26dc_yt%3D1%26kga%3D-1%26kgg%3D-1%26klg%3Den%26kmyd%3Dvideo-masthead%26ytdevice%3D1%26ytexp%3D9474594,23725219,9422596,9486214,23720102,9471239,23721961,23716650,9471655,9475698,23704846,9462703,23705778,23720307,9474357,23713912,23719587,9488991,9477942%26kbsg%3DHPIN180212&d_imp=1&ytdevice=1&pucrd=CgYIABAAGAB4Ag&correlator=3922410836762688 could not be found in this collection.

I think the thumbnails we can fix. Would you like to give it a shot?

**Comment by aishpant** [comment]
When I start https://youtube.com with Servo, I see a sparse website with no banners or video thumbnails. I cannot interact with the site; no links are clickable. I also tested with google.com and reddit.com, but they look fine.

Screenshot is attached. I am guessing this is not normal behaviour?

screenshot from 2018-02-17 01-05-34

**Comment by asajeffrey** [comment]
Hmm, no that's not to be expected, and isn't what's happening at my end. I suspect google is doing something location-specific based on IP address, sigh.

My previous niggles were just niggling, I think the easiest thing to do is just merge! If you rebase, I'll merge.

**Comment by aishpant** [comment]
I have rebased and pushed the changes.

**Comment by asajeffrey** [comment]
Thanks!

**Pull request merged**
