### PR TITLE
add 360 archive

### PR DESCRIPTION
**Pull request by anjia**
add 360 archive

### CODE REVIEW

**Comment by anjia** [comment]
#48

There are some errors in the terminal when using servo to access https://www.360.cn/.  
Could you please help me check the commit results?  @asajeffrey 
Thanks ahead.

```shell
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.13/lib/libproxychains4.dylib
ERROR 2018-08-07T11:15:25Z: script::dom::bindings::error: Error at http://localhost:8321/static/default_banner.js:50:22 Value is not an object.
ERROR 2018-08-07T11:15:27Z: script::dom::bindings::error: Error at http://localhost:8321/static/wombat.js:1605:1 SVGElement is not defined
ERROR 2018-08-07T11:15:29Z: script::dom::bindings::error: Error at http://localhost:8321/360/record/js_///s.ssl.qhmsg.com/!b9cea183/lightbox.js:12:61 jQuery is not defined
ERROR 2018-08-07T11:15:29Z: script::dom::bindings::error: Error at http://localhost:8321/360/record/mp_/https://www.360.cn/:110:61 jQuery is not defined
ERROR 2018-08-07T11:15:29Z: script::dom::bindings::error: Error at http://localhost:8321/360/record/mp_/https://www.360.cn/:124:61 jQuery is not defined
ERROR 2018-08-07T11:15:29Z: script::dom::bindings::error: Error at http://localhost:8321/360/record/mp_/https://www.360.cn/:165:276 $ is not defined
ERROR 2018-08-07T11:15:29Z: script::dom::bindings::error: Error at http://localhost:8321/360/record/mp_/https://www.360.cn/:179:72 $ is not defined
ERROR 2018-08-07T11:15:29Z: script::dom::bindings::error: Error at http://localhost:8321/360/record/mp_/https://www.360.cn/:193:61 jQuery is not defined
ERROR 2018-08-07T11:15:29Z: script::dom::bindings::error: Error at http://localhost:8321/360/record/mp_/https://www.360.cn/:206:61 jQuery is not defined
ERROR 2018-08-07T11:15:29Z: script::dom::bindings::error: Error at http://localhost:8321/360/record/mp_/https://www.360.cn/:219:61 jQuery is not defined
ERROR 2018-08-07T11:15:29Z: script::dom::bindings::error: Error at http://localhost:8321/360/record/mp_/https://www.360.cn/:240:114 $ is not defined
```

**Comment by asajeffrey** [comment]
LGTM! The errors aren't anything to worry about. @bors-servo r+

**Comment by anjia** [comment]
Okey, I got it. Thanks for your review. @asajeffrey

I notice that @bors-servo had been reminded. But I think it would be better to supplement some additional information. The screenshots are as follows.

360 1 nav
360 2 image-hover
360 3 ico-text-align
360 4 foot-info

- At position 1, the positons of arrows and icos, wrapping
- At position 2, there is a thrashing when hovering the image.
- At position 3, alignment
- At position 4, wrapping


Hope these info are helpful for servo.

**Comment by asajeffrey** [comment]
Thanks!

**Pull request merged**
