### PR TITLE
Add Reddit archive

### PR DESCRIPTION
**Pull request by mcarolan**
Implements #14 

I've added a section to `README.md` because a default install of `proxychains` on Fedora didn't have a configuration that would cause it to hit the `wayback` proxy server

Thanks for this issue, it was a great way to get a servo dev environment up and running :)

### CODE REVIEW

**Comment by asajeffrey** [comment]
Could you pull out the additions to the README? I'm a bit surprised it's needed because there should be a proxychains configuration file in the repo. Perhaps the repo should be clearer that you need to run get proxychains to use the bundled conf?

**Comment by asajeffrey** [comment]
The reddit archive looks great btw, it can be merged in if we take out the changes to the README. The README probably needs clarified, but that's a different PR!

**Comment by mcarolan** [comment]
Ahh sorry, I missed that. Have reverted the `README.md` change! thanks 👍

**Comment by asajeffrey** [comment]
Thanks!

**Pull request merged**
